# Tensorflow2.0 小练习

In [4]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [5]:
def softmax(x):
    # 稳定数值：减去最大值防止溢出
    x_shift = x - tf.reduce_max(x, axis=-1, keepdims=True)
    exp_x = tf.exp(x_shift)
    prob_x = exp_x / tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [6]:
def sigmoid(x):
    prob_x = 1.0 / (1.0 + tf.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [7]:
def softmax_ce(x, label):
    # x: 已经为 softmax 概率，[batch, classes]
    eps = 1e-12
    x_clipped = tf.clip_by_value(x, eps, 1. - eps)
    loss = -tf.reduce_mean(tf.reduce_sum(label * tf.math.log(x_clipped), axis=-1))
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [8]:
def sigmoid_ce(x, label):
    # x: 已经为 sigmoid 概率，[batch]
    eps = 1e-12
    x_clipped = tf.clip_by_value(x, eps, 1. - eps)
    loss = -tf.reduce_mean(label * tf.math.log(x_clipped) + (1. - label) * tf.math.log(1. - x_clipped))
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print(label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 1. 0. 1. 1. 0. 1. 1. 1. 0.]


True